ignored = [
  "github.com/openshift-metalkube/kni-installer/pkg/terraform/exec/plugins*",
  "golang.org/x/net*"
]

required = [
  "github.com/hashicorp/terraform/helper/acctest",
  "github.com/hashicorp/terraform/helper/customdiff",
  "github.com/hashicorp/terraform/helper/schema",
  "github.com/hashicorp/terraform/helper/resource",
  "github.com/hashicorp/terraform/helper/encryption"
]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/hashicorp/logutils"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  revision = "v0.12.0-rc1"

[[constraint]]
  name = "github.com/mitchellh/cli"
  version = "1.0.0"

# Due to dep's inabiltiy to read go modules correclty overrides are required.

# https://github.com/hashicorp/terraform/blob/v0.12.0-rc1/go.mod#L60
[[override]]
  name = "github.com/hashicorp/go-version"
  revision = "v1.1.0"

# https://github.com/hashicorp/terraform/blob/v0.12.0-rc1/go.mod#L63
[[override]]
  name = "github.com/hashicorp/hcl2"
  revision = "640445e16309fe82c7df763cbfa874485b5ca885"

# https://github.com/hashicorp/terraform/blob/v0.12.0-rc1/go.mod#L110
[[override]]
  name = "github.com/zclconf/go-cty"
  revision = "d36a6f0dbffd109d058c5d1fc16e74bad85fa96f"

# https://github.com/hashicorp/terraform/blob/v0.12.0-rc1/go.mod#L5
[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "v21.3.0"

# https://github.com/hashicorp/terraform/blob/v0.12.0-rc1/go.mod#L6
[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "v10.15.4"

# https://github.com/hashicorp/terraform/blob/v0.12.0-rc1/go.mod#L37
[[override]]
  name = "github.com/gophercloud/gophercloud"
  revision = "bc37892e196848d7d56ba0db974ba1d7d5c43b2a"

# https://github.com/hashicorp/terraform/blob/v0.12.0-rc1/go.mod#L38
[[override]]
  name = "github.com/gophercloud/utils"
  revision = "fbb6ab446f0167dfa4d25b8eb0c0d2f873924516"

# https://github.com/hashicorp/terraform/blob/v0.12.0-rc1/go.mod#L55
[[override]]
  name = "github.com/hashicorp/go-retryablehttp"
  revision = "v0.5.2"

# https://github.com/hashicorp/terraform/blob/v0.12.0-rc1/go.mod#L46
[[override]]
  name = "github.com/hashicorp/go-azure-helpers"
  revision = "166dfd221bb20c95f9db5be961c647a67646831e"

# https://github.com/hashicorp/terraform/blob/v0.12.0-rc1/go.mod#L54
[[override]]
  name = "github.com/hashicorp/go-plugin"
  revision = "5692942914bbdbc03558fde936b1f0bc2af365be"

# https://github.com/hashicorp/terraform/blob/v0.12.0-rc1/go.mod#L58
[[override]]
  name = "github.com/hashicorp/go-tfe"
  revision = "v0.3.16"

# https://github.com/hashicorp/terraform/blob/v0.12.0-rc1/go.sum#L190
[[override]]
  name = "github.com/hashicorp/go-slug"
  revision = "v0.3.0"

# https://github.com/hashicorp/terraform/blob/v0.12.0-rc1/go.mod#L103
[[override]]
  name = "github.com/terraform-providers/terraform-provider-openstack"
  revision = "v1.15.0"